language: node_js
node_js: 10

cache: yarn

before_install:
- if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then travis_terminate 0; fi
- export TZ='Asia/Shanghai'
- phpenv global 7.3.3
- git config --global user.name "Pig Fang"
- git config --global user.email "g-plane@hotmail.com"

install:
- yarn

script:
- mkdir .dist
- node --experimental-modules build.mjs
- cd .dist
- git init
- git add .
- git commit -m "Publish"
- git remote add origin https://blessing-skin:$AZURE_TOKEN@dev.azure.com/blessing-skin/Plugins/_git/Plugins
- git push -f origin master
