language: node_js
node_js: 10

cache: yarn

before_install:
- if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then travis_terminate 0; fi
- export TZ='Asia/Shanghai'
- phpenv global 7.1.11
- git config --global user.name "Pig Fang"
- git config --global user.email "g-plane@hotmail.com"

install:
- yarn

script:
- git clone https://blessing-skin:$AZURE_TOKEN@dev.azure.com/blessing-skin/Plugins/_git/Plugins .dist
- node build.js
- cd .dist
- git add .
- git commit -m "Publish"
- git push origin master
