trigger:
- master

pr: none

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: yarn
  displayName: 'Yarn'

- script: pwsh ./publish.ps1
  displayName: 'Publish plugins'
