trigger:
- master

pr: none

pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: self
  submodules: true

- script: yarn
  displayName: 'Yarn'

- pwsh: ./build.ps1
  displayName: 'Build plugins'

- pwsh: ./publish.ps1
  displayName: 'Publish plugins'
