trigger:
- master

pr: none

pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: self
  submodules: true

- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: yarn
  displayName: 'Yarn'

- pwsh: ./publish.ps1
  displayName: 'Publish plugins'
