generate-config: Generate Config

mod-requirement: MOD Requirement
mod-intro: |
  <p>We support all versions of <a href="http://www.mcbbs.net/forum.php?mod=viewthread&tid=358932" target="_blank">UniSkinMod</a> and <a href="http://www.mcbbs.net/thread-269807-1-1.html" target="_blank">CustomSkinLoader</a>, and any other skin mod supporting leagcy links.</p>
  <p>Detailed documentation is available at: <a href="https://github.com/printempw/blessing-skin-server/wiki/%E5%A6%82%E4%BD%95%E9%85%8D%E7%BD%AE%E7%9A%AE%E8%82%A4-Mod" target="_blank">@GitHub</a></p>
version: Version
config-file: Config File

extra-list-intro: |
  ExtraList (supported by CustomSkinLoader 14.4+) is designing for providing a faster and more convenient way to add custom skin servers. Just download the ExtraList file below and put it into <code>.minecraft/CustomSkinLoader/ExtraList</code> directory. Restart the Minecraft, and it's done!
extra-list-download: Click to download ExtraList
