generate-config: 配置生成

mod-requirement: Mod 需求
mod-intro: |
  <p>本站支持的皮肤 Mod 有 <a href="http://www.mcbbs.net/forum.php?mod=viewthread&tid=358932" target="_blank">UniSkinMod</a>，<a href="http://www.mcbbs.net/thread-269807-1-1.html" target="_blank">CustomSkinLoader</a> 各自的新版和旧版，以及任何支持传统皮肤加载链接的皮肤 Mod。</p>
  <p>详细教程请参阅：<a href="https://github.com/bs-community/blessing-skin-server/wiki/%E5%A6%82%E4%BD%95%E9%85%8D%E7%BD%AE%E7%9A%AE%E8%82%A4-Mod" target="_blank">@GitHub</a></p>
version: 版本
config-file: 配置文件

extra-list-intro: |
  ExtraList 是 CustomSkinLoader（14.4 以上版本）提供的快捷添加皮肤站功能。不需要任何繁琐的配置修改，您只需要下载下面提供的 ExtraList 文件，放入 <code>.minecraft/CustomSkinLoader/ExtraList</code> 目录下并重启游戏即可。
  <br>在安装完成第一次启动游戏并成功载入 CustomSkinLoader 后 ExtraList 文件会被自动删除，这是正常现象。此时 :site 已被添加至 CustomSkinLoader 加载列表的顶部。
extra-list-download: 点击下载 ExtraList 文件
